owner: MigraineKR
repo: jhs.status

sites:
  - name: jhsnet.net
    url: https://www.jhsnet.net/
  - name: jhsnet.net/english
    url: https://www.jhsnet.net/english.html
  - name: zutsu-online.jp
    url: https://zutsu-online.jp/
        
status-website:
  cname: jhs.status.migraine.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | JHS
  introTitle: "**Status** for Japanese Headache Society"
  introMessage: 日本頭痛学会 ウェブモニター
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.jhsnet.net/
    - title: Newsletter
      href: https://www.jhsnet.net/newsletter.html
    - title: JPAC
      href: https://www.jhsnet.net/pdf/jpac_index.pdf
    - title: Headache Diary
      href: https://www.jhsnet.net/pdf/headachediary.pdf
