owner: MigraineKR
repo: jhs.status

sites:
  - name: jhsnet.net
    url: https://www.jhsnet.net/
  - name: jhsnet.net/english
    url: https://www.jhsnet.net/english.html
        
status-website:
  cname: jhs.status.migraine.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | Japanese Headache Society
  introTitle: "**Status** for Japanese Headache Society"
  introMessage: 日本頭痛学会 ウェブモニター
  navbar:
    - title: Status
      href: /
